Feature/53/handle peer disconnection
SaitoTech/saito-rust-workspace pull request #57
Opened 2022-05-18 17:41 UTC by tharindal

2022-05-20 04:03 UTC, SankaD requested changes

2022-05-20 04:03 UTC, SankaD commented on saito-rust/src/saito/network_controller.rs
> +            warn!("failed connecting to peer : {:?}", peer); //TODO : Retry connecting after an interval
you can setup clion to auto format with rustfmt. I think this line will break into 2 after formatting.

2022-05-23 08:11 UTC, tharindal commented on saito-core/src/core/routing_controller.rs
> +                self.io_interface.connect_to_peer(peer.static_peer_config.as_ref().unwrap().clone()).await.unwrap();
Isn't that going to be handled inside the network_controller ? if we are going to retry with timers isn't it the best place to do so?

2022-05-23 08:32 UTC, tharindal commented on saito-core/src/core/data/peer_collection.rs
> +    pub fn find_peer_by_index(&self, peer_index : u64) -> Option<&Peer> {
Is there any advantage here ?

2022-05-23 08:49 UTC, tharindal commented on saito-core/src/core/data/peer_collection.rs
> +    pub fn find_peer_by_index(&self, peer_index : u64) -> Option<&Peer> {
Ignoring as per your feedback

2022-05-24 06:08 UTC, SankaD approved these changes

2022-05-24 06:28 UTC, SankaD approved these changes

2022-05-24 06:34 UTC, merged