Feature/549/prune blocks
SaitoTech/saito-rust-workspace pull request #597
Opened 2023-10-30 13:18 UTC by davikstone2

2023-11-06 06:29 UTC, SankaD requested changes

2023-11-06 06:29 UTC, SankaD commented on saito-core/src/core/data/transaction.rs
> +                if *hash != [0; 32] {
does this mean hash should be [0;32] ?

2023-11-06 06:29 UTC, SankaD commented on saito-core/src/core/data/merkle.rs
> +                    // Decide what to do with right_leaf - here we're discarding it
is this TODO ?

2023-11-06 06:29 UTC, SankaD commented on saito-core/src/core/data/block.rs
> +    // pub fn validate_spv_transaction(&self, spv_tx: &Transaction) -> bool {
remove if these are not needed

2023-11-06 11:34 UTC, davikstone2 commented on saito-core/src/core/data/block.rs
> +        while !no_simplification_needed {
there is a unit test "generate_lite_block_test" already for this

2023-11-06 11:34 UTC, davikstone2 commented on saito-core/Cargo.toml
> +sha2 = "0.9"
removed

2023-11-06 11:35 UTC, davikstone2 commented on saito-core/src/core/data/merkle.rs
> +                    // Decide what to do with right_leaf - here we're discarding it
updated

2023-11-06 11:35 UTC, davikstone2 commented on saito-core/src/core/data/transaction.rs
> +                if *hash != [0; 32] {
updated

2023-11-15 22:04 UTC, SankaD requested changes

2023-11-15 22:04 UTC, SankaD commented on saito-rust/data/issuance/test/KEY
> +
what's this?

2023-11-15 22:04 UTC, SankaD commented on saito-rust/data/.gitignore
> +# /issuance/test/
why remove these ?

2023-11-20 12:28 UTC, SankaD requested changes

2023-11-20 12:28 UTC, SankaD commented on saito-core/src/core/data/block.rs
> +    #[ignore]
what's this ?

2023-11-20 12:28 UTC, SankaD commented on saito-core/src/core/data/block.rs
> +                    signature: tx.signature.clone(),
clone() is not required

2023-11-20 12:28 UTC, SankaD commented on saito-core/src/core/data/block.rs
> +                    hash_for_signature: tx.hash_for_signature.clone(),
clone is not required

2023-11-20 12:28 UTC, SankaD commented on saito-rust/data/issuance/test/issuance
> +99500	i5Gh5B9K5TuC8ZN25Up3YGPvy5ikzZP1aNwGJ6WRGDLx	Normal
add this file to gitignore please

2023-11-21 14:51 UTC, SankaD approved these changes

2023-11-21 16:17 UTC, merged