Feature/653/clone
SaitoTech/saito-rust-workspace pull request #663
Opened 2024-02-19 16:09 UTC by davikstone2

2024-02-20 05:22 UTC, SankaD requested changes

2024-02-20 05:22 UTC, SankaD commented on scripts/bootstrap_linux.sh
>  cargo build
better to add a step to install cargo/rust and other required tools before this

2024-02-20 05:22 UTC, SankaD commented on scripts/bootstrap_linux.sh
>  cargo build
better to ask from user before each install though

2024-02-23 02:11 UTC, SankaD commented on scripts/initial_setup.sh
> +
- [ ] if a software is already installed, skip to next step without the prompt. \
- [ ] wasm-pack is an optional requirement for wasm compilation. skip that when running initial_setup script

2024-02-28 01:39 UTC, arpee commented
What am I testing?

2024-02-28 02:27 UTC, arpee commented
Notes:

 - we should not be offering 'connected' nodes to users right now. (These risk bringing down prod).
  (if we do want to keep connected we should maybe offer connection to the _test_ or _staging_ networks.)
 - "isolated node" is confusing "local development node" would be better
 - output paths should be relative so the users knows where things are happening. eg: `config.json has been created from config.template.json.` does not tell the user _where_ these files are...  `./config/config.json` has been created from `./config/config.template.json` is clear.
 - ```blocks folder has been created.
issuance file has been created from issuance.template.
Running bootstrap_linux.sh for Linux
``` same issue. Also what does this script do? 'Installing requirements' or similar helpful so I know what the script is doing. (nice OS detection)
- No need for: ```
chmod +x "$SCRIPT_DIR/bootstrap_mac.sh"
chmod +x "$SCRIPT_DIR/bootstrap_linux.sh"
``` we can just commit the files as executable (I have done this - working on linux).

 - why do I need root to run the node? (nice user permissions detection)
 - `Please answer yes or no.` usually the options are given with capital `... (y/N)` or `...(Y/n)` for the default allowing an enter to move forward and a headless install with all options default to be created later. 
 - Note: `sudo: apt: command not found` we might want to note that this is a deb/ubuntu only script.
 - Is there a reason we don't just add a `./data/blocks/.gitkeep` file in the blocks folder and then just have it empty in the repo?
 - ```# Start node
cd "$BASE_PATH"

echo "Running 'RUST_LOG=debug cargo run' in $BASE_PATH"
env RUST_LOG=debug cargo run
``` we can check if the user want's to start the node, and just give them instructions on how to do that later if they don't want to. (Also we should explain how to end the process).

2024-03-05 18:58 UTC, SankaD approved these changes

2024-03-05 18:59 UTC, merged